# baseURL
@baseURL = http://localhost:8080/auth

###
# User SIGNUP
POST {{ baseURL }}/signup
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}

###
# User LOGIN
POST {{ baseURL }}/login
Content-Type: application/json

{
    "email": "member@test.com",
    "password": "password"
}

###
# User LOGOUT
POST {{ baseURL }}/logout
Content-Type: application/json
Cookie: Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU4MjZkYzc2NzI2NzM5YzVjYmFhZmYiLCJpYXQiOjE2NTAwMTA4MjEsImV4cCI6MTY1MDAxNDQyMX0.Jw2JZxYtswZ8VBd2JFUscLevOK5plvUc_XGxXEOjy5E; HttpOnly; Max-Age=3600;

###
# Verify JWT
GET {{baseURL}}/verify-jwt HTTP/1.1
Cookie: Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjU4MjZkYzc2NzI2NzM5YzVjYmFhZmYiLCJpYXQiOjE2NTAwMTA4MjEsImV4cCI6MTY1MDAxNDQyMX0.Jw2JZxYtswZ8VBd2JFUscLevOK5plvUc_XGxXEOjy5E; HttpOnly; Max-Age=3600;